[project]
name = "api"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "hirokts", email = "9495043+hirokts@users.noreply.github.com" }
]
requires-python = ">=3.12"
dependencies = [
    "libs",
    "fastapi>=0.128.0",
    "uvicorn>=0.40.0",
]

[project.scripts]
api = "api.main:main"

[build-system]
requires = ["uv_build>=0.9.12,<0.10.0"]
build-backend = "uv_build"
